services:
  mysql:
    image: mysql:8.0
    container_name: event_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: events
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: event_backend
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www:z
    environment:
    - DB_HOST=mysql
    - DB_PORT=3306
    - DB_DATABASE=events
    - DB_USERNAME=laravel
    - DB_PASSWORD=secret
    networks:
      - backend-network
      - frontend-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: event_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8000/api
    volumes:
      - ./frontend/src:/app/src:z
    networks:
      - frontend-network

networks:
  backend-network:
  frontend-network:

volumes:
  mysql_data:
  frontend_node_modules: